# Building image
FROM node:22-alpine AS builder
WORKDIR /app

COPY . .

RUN npm install
RUN npx nx run server:build-graphql-types

FROM node:22-alpine AS runner
WORKDIR /app

ARG PORT=4000
ENV PORT=${PORT}

COPY --from=builder /app .

RUN --mount=type=secret,id=firebase_credentials \
    cat /run/secrets/firebase_credentials > apps/server/src/credentials.ts

EXPOSE ${PORT}
CMD ["npx", "nx", "run", "server:serve:production"]
