# Building image
FROM node:22-alpine AS builder
WORKDIR /app

COPY ../ .

RUN npm install

RUN npx nx run server:build-graphql-types
RUN npx nx run client:build

# Serving client
FROM node:22-alpine
WORKDIR /app

RUN npm install -g serve

# As it's a new node image we need to copy the build result from the other node image (the one that was used for building)
COPY --from=builder /app/dist/apps/client /app/dist

EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
